### ISSUE TITLE
wasm-ld: not found

### ISSUE THREAD

**Issue by thetarnav** [laytan/setup-odin#30]
When trying to build to wasm, I get an error that `wasm-ld` is not found.
I believe this could be solved by adding `llvm-<version>/bin` to the PATH.
In my own script I was doing this before and it did the trick. Although it may only be the case on ubuntu.
```bash
echo "/usr/lib/llvm-14/bin" >>$GITHUB_PATH
export PATH="/usr/lib/llvm-14/bin:$PATH"
```

**Comment by laytan** [comment]
Curiously that is what should be done already: https://github.com/laytan/setup-odin/blob/fbed82c2fbba4012331d14d89eae76953a4bcb0c/src/index.js#L181 I will have to see where it is going wrong.

**Comment by laytan** [comment]
It does not add it when you are pulling a pre-compiled release (cause llvm isn't needed with releases), is that what you are doing?

**Comment by thetarnav** [comment]
yes, just this on `ubuntu-latest`
```
- uses: laytan/setup-odin@v2
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    release: latest
```
