### ISSUE TITLE
May need an update

### ISSUE THREAD

**Issue by thetarnav** [laytan/setup-odin#36]
Haven't looked into it, but the setup stopped working for me after latest release.

```yml
jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: latest
```

![image](https://github.com/laytan/setup-odin/assets/24491503/5d5319d1-6aee-410b-a0b1-430ba2828f91)
